### ISSUE TITLE
Tablayout ScrollTo function

### ISSUE THREAD

**Issue by shukerullah** [AlbertBrand/react-native-android-tablayout#6]
how to scroll tablayout programatically?

Tablayout scroll back when I select page which is of the screen.
Thanks

**Comment by AlbertBrand** [comment]
I think I see what you mean: when there are more tabs and tab scrolling is activated in the component, the tabs scroll back to the left position on every click. This probably has to do something with a measure or layout triggered by React Native. You shouldn't need to scroll the tabs yourselves. I'll have a look.

**Comment by shukerullah** [comment]
Thanks @AlbertBrand

**Comment by AlbertBrand** [comment]
It is caused by a TabLayout feature: you have to set the tabMode property to 'scrollable' to have properly scrolling tabs. Version 0.0.9 has support for it now, see the [ScrollableTabLayout example](/AlbertBrand/react-native-android-tablayout/blob/master/example/app/ScrollableTabLayout.js) on how to set the property.

**Comment by shukerullah** [comment]
@AlbertBrand thank you so much

**Comment by shukerullah** [comment]
Dear @AlbertBrand tab scrolling is not working when i set initial page position to the tab index which is off the screen.

**Comment by qntnrbns** [comment]
I am having the same issue, and I cant seem to find a work around.
